### ISSUE TITLE
How to make natural trigger

### ISSUE THREAD

**Issue by pppppkun** [RU-System-Software-and-Security/NONE#1]
Hello, I would like to use NONE to eliminate natural triggers, but I am not sure how to create them using the current code. Can you provide more detailed steps? 

On the other hand, I found that the `get_data.py` seems to indicate a corresponding file. 
`testset = npy_data.dataset(root='./dirty_label_p05_s3', train=False, transform=transform_test)`
Can you provide it?

**Comment by ZhentingWang** [comment]
Hi, pppppkun

The implementation for generating natural triggers is included in the test_natral_trojan.py. You can find the .npz file in the link provided in the readme file (https://drive.google.com/drive/folders/13oBVDijC-nweBtHw2CBbcevXemc5vTTW).

Thanks for your interests in this work.
